/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../rtk-query/types.generated';

import { api } from 'src/rtk-query/baseGraphQLApi';
module.hot?.accept();
export type GenericConfigListQueryQueryVariables = Types.Exact<{
  query: Types.UltraQueryInput;
}>;

export type GenericConfigListQueryQuery = {
  __typename?: 'Query';
  genericConfigs?: {
    __typename?: 'UltraResult';
    index?: number;
    offset?: number;
    total?: number;
    latest?: boolean;
    data?: Array<{
      __typename?: 'GenericConfig';
      id: string;
      key: string;
      config: string;
      validation: string;
    }>;
  };
};

export type GenericConfigByKeyQueryQueryVariables = Types.Exact<{
  key: Types.Scalars['String']['input'];
}>;

export type GenericConfigByKeyQueryQuery = {
  __typename?: 'Query';
  genericConfig?: {
    __typename?: 'GenericConfig';
    id: string;
    key: string;
    config: string;
    validation: string;
  };
};

export type GenericConfigUpdateMutationMutationVariables = Types.Exact<{
  key: Types.Scalars['String']['input'];
  payload: Types.MutableGenericConfigInput;
}>;

export type GenericConfigUpdateMutationMutation = {
  __typename?: 'Mutation';
  updateGenericConfig?: {
    __typename?: 'GenericConfig';
    id: string;
    key: string;
    config: string;
    validation: string;
  };
};

export type AddGenericConfigMutationMutationVariables = Types.Exact<{
  addGenericConfigInput: Types.AddGenericConfigInput;
}>;

export type AddGenericConfigMutationMutation = {
  __typename?: 'Mutation';
  addGenericConfig?: {
    __typename?: 'GenericConfig';
    id: string;
    key: string;
    config: string;
    validation: string;
  };
};

export type RemoveGenericConfigMutationMutationVariables = Types.Exact<{
  key: Types.Scalars['String']['input'];
}>;

export type RemoveGenericConfigMutationMutation = {
  __typename?: 'Mutation';
  removeGenericConfig?: boolean;
};

export type OnGenericConfigUpdatedSubscriptionSubscriptionVariables =
  Types.Exact<{
    query: Types.Scalars['String']['input'];
  }>;

export type OnGenericConfigUpdatedSubscriptionSubscription = {
  __typename?: 'Subscription';
  onGenericConfigUpdated?: Array<{
    __typename?: 'GenericConfig';
    id: string;
    key: string;
    config: string;
    validation: string;
  }>;
};

export const GenericConfigListQueryDocument = `
    query GenericConfigListQuery($query: UltraQueryInput!) {
  genericConfigs(query: $query) {
    data {
      id
      key
      config
      validation
    }
    index
    offset
    total
    latest
  }
}
    `;
export const GenericConfigByKeyQueryDocument = `
    query GenericConfigByKeyQuery($key: String!) {
  genericConfig(key: $key) {
    id
    key
    config
    validation
  }
}
    `;
export const GenericConfigUpdateMutationDocument = `
    mutation GenericConfigUpdateMutation($key: String!, $payload: MutableGenericConfigInput!) {
  updateGenericConfig(key: $key, payload: $payload) {
    id
    key
    config
    validation
  }
}
    `;
export const AddGenericConfigMutationDocument = `
    mutation AddGenericConfigMutation($addGenericConfigInput: AddGenericConfigInput!) {
  addGenericConfig(addGenericConfigInput: $addGenericConfigInput) {
    id
    key
    config
    validation
  }
}
    `;
export const RemoveGenericConfigMutationDocument = `
    mutation RemoveGenericConfigMutation($key: String!) {
  removeGenericConfig(key: $key)
}
    `;
export const OnGenericConfigUpdatedSubscriptionDocument = `
    subscription OnGenericConfigUpdatedSubscription($query: String!) {
  onGenericConfigUpdated(query: $query) {
    id
    key
    config
    validation
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: module.hot?.status() === 'apply',
  endpoints: (build) => ({
    GenericConfigListQuery: build.query<
      GenericConfigListQueryQuery,
      GenericConfigListQueryQueryVariables
    >({
      query: (variables) => ({
        document: GenericConfigListQueryDocument,
        variables,
      }),
      providesTags: (result) =>
        Array.isArray(result?.genericConfigs?.data)
          ? result.genericConfigs.data.map((i) => ({
              type: 'GenericConfig',
              id: i.key,
            }))
          : [{ type: 'GenericConfig', id: 'LIST' }],
    }),
    GenericConfigByKeyQuery: build.query<
      GenericConfigByKeyQueryQuery,
      GenericConfigByKeyQueryQueryVariables
    >({
      query: (variables) => ({
        document: GenericConfigByKeyQueryDocument,
        variables,
      }),
      providesTags: (result) =>
        result?.genericConfig
          ? [{ type: 'GenericConfig', id: result.genericConfig.key }]
          : [],
    }),
    GenericConfigUpdateMutation: build.mutation<
      GenericConfigUpdateMutationMutation,
      GenericConfigUpdateMutationMutationVariables
    >({
      query: (variables) => ({
        document: GenericConfigUpdateMutationDocument,
        variables,
      }),
      invalidatesTags: (result) =>
        result?.updateGenericConfig
          ? [{ type: 'GenericConfig', id: result.updateGenericConfig.key }]
          : [],
    }),
    AddGenericConfigMutation: build.mutation<
      AddGenericConfigMutationMutation,
      AddGenericConfigMutationMutationVariables
    >({
      query: (variables) => ({
        document: AddGenericConfigMutationDocument,
        variables,
      }),
      invalidatesTags: [{ type: 'GenericConfig', id: 'LIST' }],
    }),
    RemoveGenericConfigMutation: build.mutation<
      RemoveGenericConfigMutationMutation,
      RemoveGenericConfigMutationMutationVariables
    >({
      query: (variables) => ({
        document: RemoveGenericConfigMutationDocument,
        variables,
      }),
      invalidatesTags: [{ type: 'GenericConfig', id: 'LIST' }],
    }),
  }),
});

export { injectedRtkApi as api };
export const {
  useGenericConfigListQueryQuery,
  useLazyGenericConfigListQueryQuery,
  useGenericConfigByKeyQueryQuery,
  useLazyGenericConfigByKeyQueryQuery,
  useGenericConfigUpdateMutationMutation,
  useAddGenericConfigMutationMutation,
  useRemoveGenericConfigMutationMutation,
} = injectedRtkApi;
