/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../rtk-query/types.generated';

import { api } from 'src/rtk-query/baseGraphQLApi';
module.hot?.accept();
export type SettlementCashflowBlotterQueryQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<
    Array<Types.InputMaybe<Types.FilterArg>> | Types.InputMaybe<Types.FilterArg>
  >;
  page: Types.Scalars['Int']['input'];
  size: Types.Scalars['Int']['input'];
}>;

export type SettlementCashflowBlotterQueryQuery = {
  __typename?: 'Query';
  cashflowsNew: {
    __typename?: 'GraphCashFlowNew';
    results: Array<{
      __typename?: 'ResultNew';
      Cashflow?: {
        __typename?: 'CashflowInfoNew';
        Payment_Amount?: string;
        Payment_Date?: string;
        NSTP_Exception?: string;
        Pay_Receive_Indicator?: string;
      };
      Entity?: {
        __typename?: 'EntityInfo';
        Counterparty_SCI_FMCODE?: string;
        Counterparty_Client_Type?: string;
      };
    }>;
    pageInfo: {
      __typename?: 'ResultPageInfo';
      totalHits: number;
      pageNo: number;
      pageSize: number;
      lastPage: boolean;
    };
  };
};

export type SettlementGroupBlotterQueryQueryVariables = Types.Exact<{
  filter?: Types.InputMaybe<Types.GroupMsgReq>;
  page: Types.Scalars['Int']['input'];
  size: Types.Scalars['Int']['input'];
}>;

export type SettlementGroupBlotterQueryQuery = {
  __typename?: 'Query';
  groupMessages: {
    __typename?: 'GroupMessages';
    results: Array<{ __typename?: 'GroupInfo'; Id?: string }>;
    pageInfo: {
      __typename?: 'ResultPageInfo';
      totalHits: number;
      pageNo: number;
      pageSize: number;
      lastPage: boolean;
    };
  };
};

export const SettlementCashflowBlotterQueryDocument = `
    query SettlementCashflowBlotterQuery($filter: [FilterArg], $page: Int!, $size: Int!) {
  cashflowsNew(filter: $filter, page: $page, size: $size) {
    results {
      Cashflow {
        Payment_Amount
        Payment_Date
        NSTP_Exception
        Pay_Receive_Indicator
      }
      Entity {
        Counterparty_SCI_FMCODE
        Counterparty_Client_Type
      }
    }
    pageInfo {
      totalHits
      pageNo
      pageSize
      lastPage
    }
  }
}
    `;
export const SettlementGroupBlotterQueryDocument = `
    query SettlementGroupBlotterQuery($filter: GroupMsgReq, $page: Int!, $size: Int!) {
  groupMessages(filter: $filter, page: $page, size: $size) {
    results {
      Id
    }
    pageInfo {
      totalHits
      pageNo
      pageSize
      lastPage
    }
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: module.hot?.status() === 'apply',
  endpoints: (build) => ({
    SettlementCashflowBlotterQuery: build.query<
      SettlementCashflowBlotterQueryQuery,
      SettlementCashflowBlotterQueryQueryVariables
    >({
      query: (variables) => ({
        document: SettlementCashflowBlotterQueryDocument,
        variables,
      }),
    }),
    SettlementGroupBlotterQuery: build.query<
      SettlementGroupBlotterQueryQuery,
      SettlementGroupBlotterQueryQueryVariables
    >({
      query: (variables) => ({
        document: SettlementGroupBlotterQueryDocument,
        variables,
      }),
    }),
  }),
});

export { injectedRtkApi as api };
export const {
  useSettlementCashflowBlotterQueryQuery,
  useLazySettlementCashflowBlotterQueryQuery,
  useSettlementGroupBlotterQueryQuery,
  useLazySettlementGroupBlotterQueryQuery,
} = injectedRtkApi;
