/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SsiFormJsonSchema = {
  [k: string]: unknown;
} & {
  /**
   * Format: Alphabetnumberic
   */
  accountWithInstitutionAccount?: string;
  /**
   * Format: Alphabetnumberic
   */
  accountWithInstitutionAddress?: string;
  /**
   * Format: Upper Case Alphabetnumberic with length 8 or 11
   */
  accountWithInstitutionBic?: string;
  /**
   * Format: Alphabetnumberic
   */
  accountWithInstitutionCity?: string;
  /**
   * Format: Alphabetnumberic
   */
  accountWithInstitutionName?: string;
  /**
   * Format: Alphabetnumberic
   */
  beneficiaryAccount?: string;
  /**
   * Format: Alphabetnumberic
   */
  beneficiaryAddress?: string;
  /**
   * Format: Upper Case Alphabetnumberic with length 8 or 11
   */
  beneficiaryBic?: string;
  /**
   * Format: Alphabetnumberic
   */
  beneficiaryName?: string;
  /**
   * Format: Alphabetnumberic
   */
  beneficiaryName2?: string;
  charges?: 'OUR' | 'SHA' | 'BEN';
  ebbsNostroAccount?: string;
  intermediaryAccount?: string;
  /**
   * Format: Alphabetnumberic
   */
  intermediaryAddress?: string;
  /**
   * Format: Upper Case Alphabetnumberic with length 8 or 11
   */
  intermediaryBic?: string;
  /**
   * Format: Alphabetnumberic
   */
  intermediaryPostcode?: string;
  /**
   * Format: Alphabetnumberic
   */
  intermediaryName?: string;
  /**
   * Format: Alphabetnumberic
   */
  orderCustomerAccount?: string;
  /**
   * Format: Upper Case Alphabetnumberic with length 8 or 11
   */
  orderCustomerBic?: string;
  /**
   * Format: Alphabetnumberic
   */
  orderCustomerCity?: string;
  /**
   * Format: Alphabetnumberic
   */
  orderCustomerAddress?: string;
  /**
   * Format: Alphabetnumberic
   */
  orderCustomerName?: string;
  /**
   * Format: Alphabetnumberic
   */
  receiversCorrespondentAddress?: string;
  /**
   * Format: Alphabetnumberic
   */
  receiversCorrespondentName?: string;
  /**
   * Format: Alphabetnumberic
   */
  receiversCorrespondentCity?: string;
  /**
   * Format: Alphabetnumberic
   */
  receiversCorrespondentAccount?: string;
  /**
   * Format: Upper Case Alphabetnumberic with length 8 or 11
   */
  receiversCorrespondentBic?: string;
  remittanceInfomation1?: string;
  remittanceInfomation2?: string;
  remittanceInfomation3?: string;
  remittanceInfomation4?: string;
  senderToReceiver1?: string;
  senderToReceiver2?: string;
  senderToReceiver3?: string;
  senderToReceiver4?: string;
  senderToReceiver5?: string;
  senderToReceiver6?: string;
  swiftType: 'MT103' | 'MT103 SERIAL' | 'MT202';
  ssiType: 'Primary' | 'Secondary';
  settlementMeans: 'CLG' | 'CLS SUSP' | 'NOS' | 'Over-Account' | 'Non-Nostro';
  settlementAccount: string;
  coveredPayment?: boolean;
  tpp?: boolean;
  [k: string]: unknown;
};
